intern = "learning Python"
print(intern.lower())
print()
print(intern.upper())
print()
print(intern.strip("n"))
print()
print(intern.replace("Python", "Java"))
print()
words = intern.split()
print()
print(words)
print()
joined = "-".join(words)
print()
print(joined)